### ISSUE TITLE
The theme link in README doesn't work

### ISSUE THREAD

**Issue by clbn** [yithian/slate-theme#1]
The link `https://listed.to/p/jxK2teM5lU` doesn't seem to work on the import. (And if opened in browser, it redirects to the `listed.to` homepage.)

**Comment by yithian** [comment]
Apologies! https://blog.yuggoth.space/p/fvqXJWJqYi should work.

I've updated the README to match.

**Comment by clbn** [comment]
Thanks, this one works!
