### ISSUE TITLE
Thank you! Theme for Chrome, maybe?

### ISSUE THREAD

**Issue by gxcodes** [yithian/slate-theme#5]
Hi just wanted to say that I love your theme and I use both the standard-notes and firefox theme. However, I'm more into Brave browser (chromium based and can use chrome themes/extensions) these days. Any plan to develop slate for chrome?

I know nothing about browser theme development but I know a thing or two about html/css, let me know if I can be of help, that'd be awesome!

**Comment by yithian** [comment]
Heya - glad you're enjoying the theme!

I haven't used Chrome/Chromium based browsers much, so theming them with Slate wasn't something I had considered. I'll take a look and see what I can put together!

**Comment by yithian** [comment]
note to self: [this doc](https://developer.chrome.com/docs/extensions/mv3/themes/) seems like the one to go on

**Comment by gxcodes** [comment]
> note to self: [this doc](https://developer.chrome.com/docs/extensions/mv3/themes/) seems like the one to go on

Super! I'll have a look too this weekend.

**Comment by yithian** [comment]
ok, i've submitted the theme to the chrome store for review!

i'll update (and close) this issue once it goes live

**Comment by yithian** [comment]
the slate chrome theme is live in the web store! you can grab it [here](https://chrome.google.com/webstore/detail/slate/kjkpbieadgoimbamhfegffpdcdcjkcmi)

i don't really use chromium-based browsers much, so some details may be less than ideal. if you run into something you'd like to see tweaked, please open up another issue here :)

**Comment by gxcodes** [comment]
Not only it's beautiful, that was super fast too! Thank you!
